package com.ness.screening.entity;

// Generated Jul 13, 2012 11:13:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AppCode generated by hbm2java
 */
@Entity
@Table(name = "appcode", catalog = "Ness_Tech_Screen")
public class AppCode implements java.io.Serializable {

	private Integer idAppcode;
	private String category;
	private String shortCode;
	private String name;
	private String description;
	private boolean status;

	private User createdBy;
	private User updatedBy;
	private Date createdDt;
	private Date updatedDt;
	public AppCode() {
	}

	public AppCode(String shortCode, String name, boolean status) {
		this.shortCode = shortCode;
		this.name = name;
		this.status = status;
	}

	public AppCode(String category, String shortCode, String name,
			String description, boolean status) {
		this.category = category;
		this.shortCode = shortCode;
		this.name = name;
		this.description = description;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "AppCode_id", unique = true, nullable = false)
	public Integer getIdAppcode() {
		return this.idAppcode;
	}

	public void setIdAppcode(Integer idAppcode) {
		this.idAppcode = idAppcode;
	}

	@Column(name = "Category", length = 100)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "short_Code", nullable = false, length = 3)
	public String getShortCode() {
		return this.shortCode;
	}

	public void setShortCode(String shortCode) {
		this.shortCode = shortCode;
	}

	@Column(name = "Name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Description", length = 225)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status", nullable = false)
	public boolean getStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToOne(cascade=CascadeType.ALL,fetch=FetchType.EAGER)
    @JoinColumn(name="created_By_id",insertable=true,
        updatable=true,nullable=true,unique=true)
	public User getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(User createdBy) {
		this.createdBy = createdBy;
	}

	@OneToOne(cascade=CascadeType.ALL,fetch=FetchType.EAGER)
    @JoinColumn(name="updated_by_Id",insertable=true,
        updatable=true,nullable=true,unique=true)
	public User getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(User updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_dt")
	public Date getCreatedDt() {
		return createdDt;
	}

	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_dt")
	public Date getUpdatedDt() {
		return updatedDt;
	}

	public void setUpdatedDt(Date updatedDt) {
		this.updatedDt = updatedDt;
	}

}
