package com.ness.screening.entity;

// default package
// Generated Dec 22, 2015 3:05:04 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Candidate generated by hbm2java
 */
@Entity
@Table(name = "job_requirements", catalog = "Ness_Tech_Screen")
public class JobRequirements implements java.io.Serializable {

	private Integer JobReqId;
	private String jobReqTitle;
	private String jobReqDesc;
	private String jobDuration;
	private String billRate;
	private String jobLocation;
	private Client client;
	private User createdBy;
	private User updatedBy;
	private Date createdDt;
	private Date updatedDt;
	
	public JobRequirements() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Job_requirements_id", unique = true, nullable = false)
	public Integer getJobReqId() {
		return JobReqId;
	}

	public void setJobReqId(Integer jobReqId) {
		JobReqId = jobReqId;
	}

	@Column(name = "Job_requirements_Title")
	public String getJobReqTitle() {
		return jobReqTitle;
	}

	public void setJobReqTitle(String jobReqTitle) {
		this.jobReqTitle = jobReqTitle;
	}

	
	@Column(name = "Job_requirements_desc")
	public String getJobReqDesc() {
		return jobReqDesc;
	}

	public void setJobReqDesc(String jobReqDesc) {
		this.jobReqDesc = jobReqDesc;
	}

	@Column(name = "Job_duration")
	public String getJobDuration() {
		return jobDuration;
	}

	public void setJobDuration(String jobDuration) {
		this.jobDuration = jobDuration;
	}

	@Column(name = "Bill_rate")
	public String getBillRate() {
		return billRate;
	}

	public void setBillRate(String billRate) {
		this.billRate = billRate;
	}

	@Column(name = "Job_Location")
	public String getJobLocation() {
		return jobLocation;
	}

	public void setJobLocation(String jobLocation) {
		this.jobLocation = jobLocation;
	}


	@OneToOne(cascade=CascadeType.ALL,fetch=FetchType.EAGER)
    @JoinColumn(name="Client_id",insertable=true,
        updatable=true,nullable=true,unique=true)
	public Client getClient() {
		return client;
	}


	public void setClient(Client client) {
		this.client = client;
	}

	@OneToOne(cascade=CascadeType.ALL,fetch=FetchType.EAGER)
    @JoinColumn(name="created_By_id",insertable=true,
        updatable=true,nullable=true,unique=true)
	public User getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(User createdBy) {
		this.createdBy = createdBy;
	}

	@OneToOne(cascade=CascadeType.ALL,fetch=FetchType.EAGER)
    @JoinColumn(name="updated_by_Id",insertable=true,
        updatable=true,nullable=true,unique=true)
	public User getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(User updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_dt")
	public Date getCreatedDt() {
		return createdDt;
	}

	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_dt")
	public Date getUpdatedDt() {
		return updatedDt;
	}

	public void setUpdatedDt(Date updatedDt) {
		this.updatedDt = updatedDt;
	}

	
	

	
}
