package com.ness.screening.entity;

// default package
// Generated Dec 22, 2015 3:05:04 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "user_role", catalog = "Ness_Tech_Screen", uniqueConstraints = @UniqueConstraint(columnNames = "User_Role_Name"))
public class UserRole implements java.io.Serializable {

	private Integer userRoleId;
	private String userRoleName;
	private Byte userRoleStatus;

	public UserRole() {
	}

	public UserRole(String userRoleName, Byte userRoleStatus) {
		this.userRoleName = userRoleName;
		this.userRoleStatus = userRoleStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "User_Role_Id", unique = true, nullable = false)
	public Integer getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(Integer userRoleId) {
		this.userRoleId = userRoleId;
	}

	@Column(name = "User_Role_Name", unique = true, length = 45)
	public String getUserRoleName() {
		return this.userRoleName;
	}

	public void setUserRoleName(String userRoleName) {
		this.userRoleName = userRoleName;
	}

	@Column(name = "User_Role_Status")
	public Byte getUserRoleStatus() {
		return this.userRoleStatus;
	}

	public void setUserRoleStatus(Byte userRoleStatus) {
		this.userRoleStatus = userRoleStatus;
	}


	

	
}
