package com.ness.screening.entity;

// default package
// Generated Dec 22, 2015 3:05:04 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "Ness_Tech_Screen", uniqueConstraints = {
		@UniqueConstraint(columnNames = "User_Email_Id"),
		@UniqueConstraint(columnNames = "User_Name") })
public class User implements java.io.Serializable {

	private Integer userId;
	private String userName;
	private String userEmailId;
	private String userPhoneNo;
	private String userFirstName;
	private String userLastName;
	private String userEmpId;
	private String password;
	private UserRole userRole;
	private String role;

	public User() {
	}

	public User(String userName, String userEmailId, String userPhoneNo,
			String userFirstName, String userLastName, String userEmpId,
			UserRole userRole,String password) {
		this.userName = userName;
		this.userEmailId = userEmailId;
		this.userPhoneNo = userPhoneNo;
		this.userFirstName = userFirstName;
		this.userLastName = userLastName;
		this.userEmpId = userEmpId;
		this.userRole = userRole;
		this.password=password;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "User_Id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "User_Name", unique = true, length = 200)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "User_Email_Id", unique = true, length = 200)
	public String getUserEmailId() {
		return this.userEmailId;
	}

	public void setUserEmailId(String userEmailId) {
		this.userEmailId = userEmailId;
	}

	@Column(name = "User_Phone_no", length = 20)
	public String getUserPhoneNo() {
		return this.userPhoneNo;
	}

	public void setUserPhoneNo(String userPhoneNo) {
		this.userPhoneNo = userPhoneNo;
	}

	@Column(name = "User_First_Name", length = 100)
	public String getUserFirstName() {
		return this.userFirstName;
	}

	public void setUserFirstName(String userFirstName) {
		this.userFirstName = userFirstName;
	}

	@Column(name = "User_Last_Name", length = 100)
	public String getUserLastName() {
		return this.userLastName;
	}

	public void setUserLastName(String userLastName) {
		this.userLastName = userLastName;
	}

	@Column(name = "User_Emp_Id", length = 45)
	public String getUserEmpId() {
		return this.userEmpId;
	}

	public void setUserEmpId(String userEmpId) {
		this.userEmpId = userEmpId;
	}

	@OneToOne(cascade=CascadeType.ALL,fetch=FetchType.EAGER)
    @JoinColumn(name="USER_ROLE_ID",insertable=true,
        updatable=true,nullable=true,unique=true)
	public UserRole getUserRole() {
		return userRole;
	}

	public void setUserRole(UserRole userRole) {
		this.userRole = userRole;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Transient
	public String getRole() {
		if(role==null){
			this.role=userRole.getUserRoleName();
		}
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	
	
}
