package com.ness.screening.entity;

// default package
// Generated Dec 22, 2015 3:05:04 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Candidate generated by hbm2java
 */
@Entity
@Table(name = "vendor", catalog = "Ness_Tech_Screen")
public class Vendor implements java.io.Serializable {

	private Integer vendorId;
	private String vendorName;
	private String vendorContactFirstName;
	private String vendorContactLastName;
	private String vendorEmailId;
	private String vendorContactNum;
	private Set<Candidate> candidates = new HashSet<Candidate>();
	private User createdBy;
	private User updatedBy;
	private Date createdDt;
	private Date updatedDt;
	
	public Vendor() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Vendor_id", unique = true, nullable = false)
	public Integer getVendorId() {
		return vendorId;
	}

	public void setVendorId(Integer vendorId) {
		this.vendorId = vendorId;
	}

	@Column(name = "Vendor_name")
	public String getVendorName() {
		return vendorName;
	}

	public void setVendorName(String vendorName) {
		this.vendorName = vendorName;
	}

	@Column(name = "Vendor_Contact_First_name")
	public String getVendorContactFirstName() {
		return vendorContactFirstName;
	}

	public void setVendorContactFirstName(String vendorContactFirstName) {
		this.vendorContactFirstName = vendorContactFirstName;
	}

	@Column(name = "Vendor_Contact_Last_name")
	public String getVendorContactLastName() {
		return vendorContactLastName;
	}

	public void setVendorContactLastName(String vendorContactLastName) {
		this.vendorContactLastName = vendorContactLastName;
	}

	@Column(name = "Vendor_Email_id")
	public String getVendorEmailId() {
		return vendorEmailId;
	}

	public void setVendorEmailId(String vendorEmailId) {
		this.vendorEmailId = vendorEmailId;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "vendor")
	public Set<Candidate> getCandidates() {
		return candidates;
	}

	public void setCandidates(Set<Candidate> candidates) {
		this.candidates = candidates;
	}

	@Column(name = "Vendor_Contact_number")
	public String getVendorContactNum() {
		return vendorContactNum;
	}

	public void setVendorContactNum(String vendorContactNum) {
		this.vendorContactNum = vendorContactNum;
	}

	@OneToOne(cascade=CascadeType.ALL,fetch=FetchType.EAGER)
    @JoinColumn(name="created_By_id",insertable=true,
        updatable=true,nullable=true,unique=true)
	public User getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(User createdBy) {
		this.createdBy = createdBy;
	}

	@OneToOne(cascade=CascadeType.ALL,fetch=FetchType.EAGER)
    @JoinColumn(name="updated_by_Id",insertable=true,
        updatable=true,nullable=true,unique=true)
	public User getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(User updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_dt")
	public Date getCreatedDt() {
		return createdDt;
	}

	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_dt")
	public Date getUpdatedDt() {
		return updatedDt;
	}

	public void setUpdatedDt(Date updatedDt) {
		this.updatedDt = updatedDt;
	}

	
	

	
}
